### ISSUE TITLE
Can not navigate to files if they are outside workspace folder

### ISSUE THREAD

**Issue by rftw** [deepakpahwa19/flow-bookmarks#17]
Hello, 

Thank you for creating this very productive extension.

I am able to create bookmarks in files that are present outside the workspace folder but I am unable to navigate to them. Clicking on the bookmarks in the extension sidebar is not taking me anywhere. 

- What I noticed is that when I exported the bookmarks, the extension is saving relative paths of files instead of absolute paths. For files that are outside workspace, the extension is truncating the absolute paths.

Ex: _"C:/Users/User/.ipython/profile_default/ipython_config.py"_ gets truncated to _"ile_default/ipython_config.py"_
 
- In developer tools, I noticed that when I clicked on the bookmark, the workspace folder path is appended to the truncated path thus leading to error _Unable to resolve non-existing file _

Can you make an option available to save and navigate absolute paths instead of relative paths.

Thank you!

**Comment by deepakpahwa19** [comment]
Glad you liked it and it is productive for you too.

It would not be possible to bookmark the file outside the workspace. Relative gives more flexibility so that bookmarks can be shared between windows and mac laptops.

I would recommend to open the common parent folder in VS code, in that way you will be able to bookmark and navigate.

Will feel good if you can provide your review on marketplace:
https://marketplace.visualstudio.com/items?itemName=DeepakPahawa.flowbookmark&ssr=false#review-details
